deleteDependentEntities: true
createMissingRelatedEntities: true
resources:
  - kind: group
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"gitlabGroup"'
          properties:
            visibility: .visibility
            url: .web_url
            description: .description

  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"project"'
          properties:
            url: .web_url
            readme: .readme_url
            description: .description
            language: .__languages
            namespace: .namespace.name
            fullPath: .namespace.full_path
            defaultBranch: .default_branch
          relations:
            group: .__group[0].id | tostring

  - kind: merge_request
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"gitlabMergeRequest"'
          properties:
            creator: .author.name
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .web_url
            reviewers: '.reviewers[] | .username'
          relations:
            service: .__project.id | tostring

  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"gitlabIssue"'
          properties:
            link: .web_url
            description: .description
            createdAt: .created_at
            closedAt: .closed_at
            updatedAt: .updated_at
            creator: .author.name
            status: .state
            labels: .labels
          relations:
            service: .__project.id | tostring
